Pipa/shop cart test save
DereviankinNikita/automation_framework_students pull request #11
Opened 2022-08-08 11:42 UTC by CyberShval

Pipa Smoke Test complete rev 1.2

2022-08-08 13:26 UTC, DereviankinNikita requested changes

2022-08-08 13:26 UTC, DereviankinNikita commented on src/test/java/testNG/TestShopCart.java
> +        do{
Please move do while block in some method in helper

2022-08-08 17:03 UTC, CyberShval commented on src/test/java/testNG/TestShopCart.java
> +        do{
corrected

2022-08-09 12:54 UTC, DereviankinNikita approved these changes

2022-08-09 15:28 UTC, Nigeriobike approved these changes

2022-08-09 15:28 UTC, merged