Nigeriobike
DereviankinNikita/automation_framework_students pull request #12
Opened 2022-08-09 12:12 UTC by Nigeriobike

2022-08-09 12:53 UTC, DereviankinNikita requested changes

2022-08-09 12:53 UTC, DereviankinNikita commented on src/test/java/holders/TestInit.java
> +    @BeforeMethod
BeforeMethod?

2022-08-09 12:53 UTC, DereviankinNikita commented on testng.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Create separate directory for suites

2022-08-09 13:38 UTC, Nigeriobike commented on src/test/java/holders/TestInit.java
> +    @BeforeMethod
Yes , cos I use parameters for my test function in classes

2022-08-09 20:30 UTC, Nigeriobike commented on testng.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I can't cos of data provider

2022-08-11 12:14 UTC, DereviankinNikita commented
@Nigeriobike please fix merge conflicts

2022-08-11 17:10 UTC, Nigeriobike commented
Fixed

2022-08-15 09:47 UTC, DereviankinNikita approved these changes

2022-08-15 09:50 UTC, CyberShval approved these changes

2022-08-15 09:51 UTC, merged