Project patern
DereviankinNikita/automation_framework_students pull request #5
Opened 2022-08-04 17:25 UTC by CortUA

Example

2022-08-04 17:25 UTC, Nigeriobike approved these changes

2022-08-04 17:26 UTC, llo3iXyH approved these changes

2022-08-04 17:27 UTC, AnnaSokolenko approved these changes

2022-08-04 17:29 UTC, GREN0R approved these changes

2022-08-04 18:00 UTC, Nigeriobike approved these changes

2022-08-04 20:51 UTC, DereviankinNikita requested changes

2022-08-04 20:51 UTC, DereviankinNikita commented on src/test/java/Obj/RegPageObj.java
> +public class RegPageObj extends DriverHolder {
please rename the class using elements keyword to indicate that the elements are stored here

2022-08-04 20:56 UTC, DereviankinNikita commented
@CortUA Before merge be sure that you branch is up to date with master, currently it have a conflicts
<img width="1219" alt="Screenshot 2022-08-04 at 23 54 35" src="https://user-images.githubusercontent.com/24982210/182951070-bb5c7606-e7e9-4cec-a4e6-3b57d66cccc4.png">
<img width="843" alt="Screenshot 2022-08-04 at 23 56 09" src="https://user-images.githubusercontent.com/24982210/182951103-b3572537-5743-489f-8941-2c2b69916d02.png">

2022-08-05 22:28 UTC, AnnaSokolenko approved these changes

2022-08-05 22:45 UTC, AnnaSokolenko approved these changes

2022-08-11 12:18 UTC, DereviankinNikita commented
@CortUA if this pull request is no longer relevant please close it

2022-08-16 16:09 UTC, merged